export const REGISTER_USER = 'REGISTER_USER';
export const REGISTER_USER_SUCCESS = 'REGISTER_USER_SUCCESS';
export const REGISTER_USER_ERROR = 'REGISTER_USER_ERROR';

export const LOGIN_USER = 'LOGIN_USER';
export const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS';
export const LOGIN_USER_ERROR = 'LOGIN_USER_ERROR';

export const FORGOT_PASSWORD = 'FORGOT_PASSWORD';
export const FORGOT_PASSWORD_SUCCESS = 'FORGOT_PASSWORD_SUCCESS';

export const ADD_MEMBER = 'ADD_MEMBER';
export const ADD_MEMBER_SUCCESS = 'ADD_MEMBER_SUCCESS';

export const FETCH_MEMBERS = 'FETCH_MEMBERS';
export const FETCH_MEMBERS_SUCCESS = 'FETCH_MEMBERS_SUCCESS';

export const FETCH_MEMBER_DETAILS = 'FETCH_MEMBER_DETAILS';
export const FETCH_MEMBER_DETAILS_SUCCESS = 'FETCH_MEMBER_DETAILS_SUCCESS';
export const UPDATE_MEMBER_DETAILS = 'UPDATE_MEMBER_DETAILS';
export const UPDATE_MEMBER_DETAILS_SUCCESS = 'UPDATE_MEMBER_DETAILS_SUCCESS';

export const REMOVE_MEMBER = 'REMOVE_MEMBER';
export const REMOVE_MEMBER_SUCCESS = 'REMOVE_MEMBER_SUCCESS';

export const FETCH_ADMIN_PROFILE = 'FETCH_ADMIN_PROFILE';
export const FETCH_ADMIN_PROFILE_SUCCESS = 'FETCH_ADMIN_PROFILE_SUCCESS';
export const UPDATE_ADMIN_PROFILE = 'UPDATE_ADMIN_PROFILE';
export const UPDATE_ADMIN_PROFILE_SUCCESS = 'UPDATE_ADMIN_PROFILE_SUCCESS';
