name: Build and delpoy jasenrekisteri-frontend

on:
  push:
    branches:
    - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1

    - name: Build
      env:
        REACT_APP_API_URL: 'https://rekisteri.asteriski.fi/api/'
        REACT_APP_USE_PAYMENT: 'true'
      run: |
        npm i
        npm run build

    - name: Deploy
      uses: Pendect/action-rsyncer@v1.1.0
      env:
        DEPLOY_KEY: ${{secrets.SSH_KEY}}
      with:
        flags: '-avzr --delete'
        options: ''
        ssh_options: ''
        src: 'build/'
        dest: ${{secrets.SSH_PATH}}
